"""add render_url to characters

Revision ID: 005efd3d67f4
Revises: d4e8f2a1b9c6
Create Date: 2026-09-20 16:40:40.349713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005efd3d67f4'
down_revision: Union[str, Sequence[str], None] = 'd4e8f2a1b9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
