"""make character fields nullable and add unique constraint

Revision ID: 0c38b9a36d12
Revises: 845b06f56b68
Create Date: 2026-09-20 11:57:04.955808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c38b9a36d12'
down_revision: Union[str, Sequence[str], None] = '845b06f56b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'wow_class',
               existing_type=postgresql.ENUM('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'PALADIN', 'HUNTER', 'SHAMAN', 'DRUID', 'WARLOCK', 'MONK', 'EVOKER', 'DEMONHUNTER', 'DEATH_KNIGHT', name='characterclass'),
               nullable=True)
    op.alter_column('characters', 'race',
               existing_type=postgresql.ENUM('HUMAN', 'ORC', 'MAGHAR_ORC', 'GOBLIN', 'VULPERA', 'DWARF', 'NIGHT_ELF', 'UNDEAD', 'TAUREN', 'GNOME', 'TROLL', 'BLOOD_ELF', 'DRAENEI', 'WORGEN', 'PANDAREN', 'NIGHTBORNE', 'HIGHMOUNTAIN_TAUREN', 'VOID_ELF', 'DARK_IRON_DWARF', 'KUL_TIRAN', 'MECHAGNOME', 'DRACTHYR', 'ZANDALARI', 'LIGHTFORGED', name='characterrace'),
               nullable=True)
    op.alter_column('characters', 'role_function',
               existing_type=postgresql.ENUM('DPS_MELEE', 'DPS_RANGED', 'HEALER', 'TANK', name='characterfunction'),
               nullable=True)
    op.create_unique_constraint('uq_character_user_name_realm', 'characters', ['user_id', 'name', 'realm'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_character_user_name_realm', 'characters', type_='unique')
    op.alter_column('characters', 'role_function',
               existing_type=postgresql.ENUM('DPS_MELEE', 'DPS_RANGED', 'HEALER', 'TANK', name='characterfunction'),
               nullable=False)
    op.alter_column('characters', 'race',
               existing_type=postgresql.ENUM('HUMAN', 'ORC', 'MAGHAR_ORC', 'GOBLIN', 'VULPERA', 'DWARF', 'NIGHT_ELF', 'UNDEAD', 'TAUREN', 'GNOME', 'TROLL', 'BLOOD_ELF', 'DRAENEI', 'WORGEN', 'PANDAREN', 'NIGHTBORNE', 'HIGHMOUNTAIN_TAUREN', 'VOID_ELF', 'DARK_IRON_DWARF', 'KUL_TIRAN', 'MECHAGNOME', 'DRACTHYR', 'ZANDALARI', 'LIGHTFORGED', name='characterrace'),
               nullable=False)
    op.alter_column('characters', 'wow_class',
               existing_type=postgresql.ENUM('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'PALADIN', 'HUNTER', 'SHAMAN', 'DRUID', 'WARLOCK', 'MONK', 'EVOKER', 'DEMONHUNTER', 'DEATH_KNIGHT', name='characterclass'),
               nullable=False)
    # ### end Alembic commands ###
