"""create characters table

Revision ID: 34e6e5456960
Revises: 4eda7c8ec438
Create Date: 2026-09-13 13:44:37.223400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e6e5456960'
down_revision: Union[str, Sequence[str], None] = '4eda7c8ec438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('realm', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('is_alt', sa.Boolean(), nullable=False),
    sa.Column('wow_class', sa.Enum('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'PALADIN', 'HUNTER', 'SHAMAN', 'DRUID', 'WARLOCK', 'MONK', 'EVOKER', 'DEMONHUNTER', 'DEATH_KNIGHT', name='characterclass'), nullable=False),
    sa.Column('race', sa.Enum('HUMAN', 'ORC', 'MAGHAR_ORC', 'GOBLIN', 'VULPERA', 'DWARF', 'NIGHT_ELF', 'UNDEAD', 'TAUREN', 'GNOME', 'TROLL', 'BLOOD_ELF', 'DRAENEI', 'WORGEN', 'PANDAREN', 'NIGHTBORNE', 'HIGHMOUNTAIN_TAUREN', 'VOID_ELF', 'DARK_IRON_DWARF', 'KUL_TIRAN', 'MECHAGNOME', 'DRACTHYR', 'ZANDALARI', 'LIGHTFORGED', name='characterrace'), nullable=False),
    sa.Column('role_function', sa.Enum('DPS_MELEE', 'DPS_RANGED', 'HEALER', 'TANK', name='characterfunction'), nullable=False),
    sa.Column('profession', sa.Enum('BLACKSMITHING', 'LEATHERWORKING', 'TAILORING', 'ENGINEERING', 'INSCRIPTION', 'HERBALISM', 'MINING', 'SKINNING', 'FISHING', 'ALCHEMY', 'JEWELCRAFTING', 'ENCHANTING', 'COOKING', name='characterprofession'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
