"""create achievements table

Revision ID: 66a61441520a
Revises: 34e6e5456960
Create Date: 2026-09-13 14:06:10.128437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '66a61441520a'
down_revision: Union[str, Sequence[str], None] = '34e6e5456960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('achievement_title', sa.String(length=255), nullable=True),
    sa.Column('achievement_description', sa.Text(), nullable=False),
    sa.Column('achievement_icon', sa.String(length=255), nullable=False),
    sa.Column('account_wide', sa.Boolean(), nullable=False),
    sa.Column('character_specific', sa.Boolean(), nullable=False),
    sa.Column('repeatable', sa.Boolean(), nullable=False),
    sa.Column('wow_class', postgresql.ENUM('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'PALADIN', 'HUNTER', 'SHAMAN', 'DRUID', 'WARLOCK', 'MONK', 'EVOKER', 'DEMONHUNTER', 'DEATH_KNIGHT', name='characterclass', create_type=False), nullable=True),
    sa.Column('role_function', postgresql.ENUM('DPS_MELEE', 'DPS_RANGED', 'HEALER', 'TANK', name='characterfunction', create_type=False), nullable=True),
    sa.Column('profession', postgresql.ENUM('BLACKSMITHING', 'LEATHERWORKING', 'TAILORING', 'ENGINEERING', 'INSCRIPTION', 'HERBALISM', 'MINING', 'SKINNING', 'FISHING', 'ALCHEMY', 'JEWELCRAFTING', 'ENCHANTING', 'COOKING', name='characterprofession', create_type=False), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievements')
    # ### end Alembic commands ###
