"""fix point_transactions nullable fields

Revision ID: 86cebbf71f01
Revises: 8fc8ccabd306
Create Date: 2026-09-20 12:45:43.605561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86cebbf71f01'
down_revision: Union[str, Sequence[str], None] = '8fc8ccabd306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Añadir server_default a `active` para que PostgreSQL lo rellene
    # cuando se hace un INSERT sin especificar ese campo (ej: desde asyncpg)
    op.alter_column('point_transactions', 'active',
               existing_type=sa.Boolean(),
               server_default='true',
               nullable=False)
    op.alter_column('point_transactions', 'week_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('point_transactions', 'season_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('point_transactions', 'season_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('point_transactions', 'week_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
