"""add blizzard fields to users and is_verified to characters

Revision ID: 8fc8ccabd306
Revises: 0c38b9a36d12
Create Date: 2026-09-20 12:10:50.938935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc8ccabd306'
down_revision: Union[str, Sequence[str], None] = '0c38b9a36d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('blizzard_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('blizzard_battletag', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('blizzard_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('blizzard_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['blizzard_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'blizzard_token_expires_at')
    op.drop_column('users', 'blizzard_access_token')
    op.drop_column('users', 'blizzard_battletag')
    op.drop_column('users', 'blizzard_id')
    op.drop_column('characters', 'is_verified')
    # ### end Alembic commands ###
